[build]
  command = "npm run build"  # Replace with your build command
  publish = "build"         # Replace with your build output directory

[build.environment]
  NODE_VERSION = "16"       # Replace with the desired Node.js version
